### ISSUE TITLE
source code

### ISSUE THREAD

**Issue by vslee** [codyrocheleau/IEXCloudDotNet#1]
Are you planning to publish the source here on GitHub? Or is it going to be a binary only distribution on NuGet?

**Comment by codyrocheleau** [comment]
At the moment, I have no plans to publish the source code. I am willing to work with developers to include features in upcoming releases that will be useful to them and will be publishing a full documentation for it within the coming weeks. If you are looking for some features to be included, send me a message though the NuGet page or create a new issue here.

**Comment by jbrekle** [comment]
Please publish the source code, nobody will participate this way. If I want the code I can get it via ILSpy/dnSpy or something, you are just making it harder to contribute.
