### ISSUE TITLE
JsonSerializationException When Calling Method GetKeyStats() on Certain Stocks

### ISSUE THREAD

**Issue by TheHeadmaster** [codyrocheleau/IEXCloudDotNet#5]
Whenever I try to call the GetKeyStats() method I recieve this exception:
``
thrown: 'Newtonsoft.Json.JsonSerializationException' in Newtonsoft.Json.dll
Error converting value {null} to type 'System.Decimal'. Path 'marketcap', line 1, position 79.
``
I'm assuming because the market cap is null?

The stock that this is happening with is Western Asset Emerging Markets Debt Fund Inc. (EMD).
I can get other information such as price using the same symbol, but even calling the GetKeyStats() method breaks it. I'm not sure what other symbols also cause this error, but for me it's EMD specifically.

**Comment by codyrocheleau** [comment]
I will work on this shortly and send out a fix for it. Thanks for bringing this to my attention

**Comment by codyrocheleau** [comment]
Just pushed version 1.0.1.1 that fixes this issue you are having, plus I find a few other calls that provided the same Error. They should all be fixed now.
